# Generated by Django 5.2.7 on 2025-10-21 07:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoShows',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('car_preferences', models.JSONField(default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoShowsCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshows.autoshows')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.cars')),
            ],
        ),
        migrations.CreateModel(
            name='AutoShowsPromotions',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshow_id', models.UUIDField(null=True)),
                ('cars_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshows.autoshowscars')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoShowsSales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('autoshow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshows.autoshows')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshows.autoshowscars')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshows.autoshowspromotions')),
            ],
        ),
    ]
