# Generated by Django 5.2.7 on 2025-10-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('color', models.TextField()),
                ('body_type', models.TextField()),
                ('engine_type', models.TextField()),
                ('horse_power', models.IntegerField()),
                ('properties', models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
